### ISSUE TITLE
Determine how the data will be displayed to the user

### ISSUE THREAD

**Issue by kpvdev** [kpvdev/military-pay-comparison-calculator#8]

**Comment by kpvdev** [comment]
## Thoughts
- We should consider some users who may not like smooth scrolling
- Using a @media query, we could follow a users preferences to make this app as accessible as possible

## Possible Solution

``` css
@media (prefers-reduced-motion) {
  html {
	  scroll-behavior: auto;
	}
}
```

## Documentation

Here's some documentation on [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)
Here's some documentation on [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
